### ISSUE TITLE
Sell API Missing x-ebay-signature-key header

### ISSUE THREAD

**Issue by Fantic666** [CMS365-PTY-LTD/EbaySharp#4]
Many thanks for the API :)

EbaySharp.Controllers.EbayController ebayController = new EbaySharp.Controllers.EbayController(myactoken);
Transactions transactions = await ebayController.GetTransactions();

i got the error below 
    {
      "errorId": 215001,
      "domain": "ACCESS",
      "category": "REQUEST",
      "message": "Missing x-ebay-signature-key header",
      "longMessage": "Missing x-ebay-signature-key header to fulfill the request."
    }

**Comment by shafaqat-ali-cms365** [comment]
I will look into that, may I know what country your seller account is in? I have tested with Australia only.

**Comment by shafaqat-ali-cms365** [comment]
I have pushed a new version and included signing key support. Please have a test.
I tried to create a sandbox user in UK region but getting error, so I could not test it properly. I am in AU region and signing key is not required here.
